version: '3.8' # Specify the Docker Compose version

services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - '5432:5432'
    networks:
      - pg_network

  ### Postgres Adminer ###
  postgres_admin:
    image: dpage/pgadmin4
    container_name: postgres_admin_container
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.de
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - '5050:80'
    networks:
      - pg_network

networks:
  pg_network:
    driver: bridge
